### ISSUE TITLE
Throw on engine errors

### ISSUE THREAD

**Issue by thec0keman** [buschtoens/ember-lazy-mount#77]
Been working with this addon for a few days to get a lazy routeless engine set up in our app.  I've noticed a number of times now there was a critical error that threw inside this addon's mounting process, but was captured and not logged to the console.  However, our test suite uses the `preloadAssets` helper from `ember-asset-loader` and errors appeared as expected.

I'm not seeing anything in the code for this that would munch the error, so I'd guess this has something more to do with either the interface between this app and ember-asset-loader, or ember-asset-loader itself.

**Comment by buschtoens** [comment]
Can you maybe provide more details on how to reproduce this or ideally a repo which shows the error?

**Comment by buschtoens** [comment]
I published a new release, which _may_ fix this issue via https://github.com/buschtoens/ember-lazy-mount/commit/d30931eace08a1ca9cf39240176be8b23528523a. Can you give it a try?

**Comment by thec0keman** [comment]
Apologies for letting this go stale.

A real simple example:

`{{lazy-mount 'an-engine-that-does-not-exist'}}` -> silent failure
`{{mount 'an-engine-that-does-not-exist'}}` -> raises an exception `the engine 'an-engine-that-does-not-exist' can not be found.`

(Although 'does not exist' may not be accurate... but better: that isn't set up correctly yet)

**Comment by buschtoens** [comment]
This is actually intended behavior. If the engine cannot be loaded, e.g. because it does not exist, the error is yielded to the component block.

https://github.com/buschtoens/ember-lazy-mount/blob/a5188187d52667df85b8135952a358d91c4557f9/tests/integration/components/lazy-mount-test.js#L37-L50

Can you check, whether this works as expected?

#93 is about making this info available as a hook as well, so you can trigger something in response to a failure.

**Comment by thec0keman** [comment]
Oh interesting, I didn't know about this!  Okay, I think this should be closed then.

Thanks!
